services:
  biochirp_hcdt_service:
    build:
      context: .              # Use local ttd_service/ as build context
      dockerfile: Dockerfile
    container_name: biochirp_hcdt_service
    image: biochirp_hcdt_service:latest
    ports:
      - "8014:8014"
    environment:
      - TZ=Asia/Kolkata
    restart: unless-stopped